spring.application.name=stack-watch
server.port=8080

spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2:1.5b
spring.ai.ollama.chat.options.temperature=0.1
logging.level.org.springframework.ai.chat.client.advisor=DEBUG